version: "2.4"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:      
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "dNL9b?A-Wbq3rA_*"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: conddiz
      MYSQL_PASSWORD: "dx{M6%.VVTnnKxTR"
    ports:
      - "1182:3306"
     
  nginx-php-fpm:
    container_name: nginx-php-fpm
    image: richarvey/nginx-php-fpm:latest
    restart: always
    environment:
      - PHP_MEM_LIMIT:256M
    ports:
      - 1180:80          
    links: 
      - wordpress

  wordpress:
    image: wordpress:php7.4-fpm
    container_name: wordpress
    depends_on:
      - mysql      
    restart: always
    volumes:           
      - ./wordpress:/var/www/html/wordpress
    environment:
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_USER: conddiz
      WORDPRESS_DB_PASSWORD: "dx{M6%.VVTnnKxTR"    