version: "2"
web:
  image: nginx:latest
  container_name: nginx
  restart: always
  ports:
    - "1180:80"
  volumes:
    - ./nginx:/nginx    
  links:
    - wordpress

db:
  image: mysql:8.0
  container_name: mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: "dNL9b?A-Wbq3rA_*"
    MYSQL_PORT: 3306
    MYSQL_USER: conddiz
    MYSQL_PASSWORD: "dx{M6%.VVTnnKxTR"
    MYSQL_DATABASE: wordpress
  ports:
    - "1182:3306"
wordpress:
  image: wordpress:php7.4-fpm
  container_name: wordpress
  volumes:
    - ./www:/www/wordpress
  environment:
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_TABLE_PREFIX: cddz_
    WORDPRESS_DB_HOST: localhost
    WORDPRESS_DB_USER: conddiz
    WORDPRESS_DB_PASSWORD: "dx{M6%.VVTnnKxTR"
  links:
    - db