version: "2.4"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6380:6379"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:      
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "dx{M6%.VVTnnKxTR"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: cdz_agent
      MYSQL_PASSWORD: "-bguZE4^hYEu"
    ports:
      - "3307:3306"
     
  nginx:
    container_name: nginx
    image: richarvey/nginx-php-fpm:latest
    volumes:    
      - ./wordpress:/var/www/html/wordpress
    restart: always    
    ports:
        - 1000:80              
    links: 
      - wordpress

  wordpress:
    image: wordpress:php7.4-fpm
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 9009:9000
    depends_on:
      - mysql      
    restart: always
    
    environment:
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_USER: cdz_agent
      WORDPRESS_DB_PASSWORD: "-bguZE4^hYEu"
      