version: "2.4"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:      
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "dNL9b?A-Wbq3rA_*"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: conddiz
      MYSQL_PASSWORD: "dx{M6%.VVTnnKxTR"
    ports:
      - "1182:3306"
  
  php:
    image: wordpress:php7.4-fpm
    container_name: wordpress
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini      
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: conddiz
      WORDPRESS_DB_PASSWORD: "dx{M6%.VVTnnKxTR"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - php
    restart: always
    volumes:      
      - ./nginx.conf:/etc/nginx/conf.d/default.conf      
      - ./wordpress:/var/www/html      
      - ./logs:/var/log/nginx    
    ports:
      - 1180:80          
    environment:
       DOMAINS: 'localhost'  
  
 
    