#
# CONDDIZ Docker Compose Configuration File
#
# When updating, you will be prompted to replace this file with a new
# version; you should do this whenever possible to take advantage of
# new updates.
#
# If you need to customize this file, you can create a new file named:
#   docker-compose.override.yml
# with any changes you need to make.
#
version: "2.4"

services:
  nginx:
    #image: nginx:latest
    build: ./nginx/
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes_from:
      - php
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
    links:
      - php
    restart: always
    env_file: .env

  php:
      build: ./php/
      volumes:
        - ./php:/php
      links:
        - mysql    

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    volumes:
      - ./pma:/pma
    links:
      - mysql
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:             
      PMA_HOST: 127.0.0.1
      PMA_ARBITRARY: 1
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql      
    environment: 
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_USER: conddiz
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: yes      
    env_file: .env
    ports:
      - 3000:3306

wordpress:
    image: wordpress:php7.4-fpm
    volumes:
      - ./wordpress:/www/wordpress
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: cddz_
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_USER: conddiz
      WORDPRESS_DB_PASSWORD: password
    links:
      - mysql
    env_file: .env
