version: "2.4"

services:
web:
  image: nginx:latest
  container_name: nginx
  restart: always
  ports:
    - "1180:80"
  volumes:
    - ./www:/www
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
    - wordpress
php:
  image: php:7.4-fpm
  container_name: php-fpm
  volumes:
    - ./www:/www
  links:
    - db
db:
  image: mysql:8
  container_name: mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: "dNL9b?A-Wbq3rA_*"
    MYSQL_PORT: 3306
    MYSQL_USER: conddiz
    MYSQL_PASSWORD: "dx{M6%.VVTnnKxTR"
    MYSQL_DATABASE: wordpress
  ports:
    - "3000:3306"
wordpress:
  image: wordpress:php7.4-fpm
  volumes:
    - ./www:/www/wordpress
  environment:
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_TABLE_PREFIX: cddz_
    WORDPRESS_DB_HOST: localhost
    WORDPRESS_DB_USER: conddiz
    WORDPRESS_DB_PASSWORD: "dx{M6%.VVTnnKxTR"
  links:
    - db
